name: classfiedapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.4
  firebase_core: ^2.5.0
  cloud_firestore: ^4.4.0
  firebase_storage: ^11.0.11
  firebase_auth: ^4.2.6
  google_sign_in: ^5.4.4
  font_awesome_flutter: ^10.4.0
  intl: ^0.17.0
  image_picker: ^0.8.6+1
  permission_handler: ^10.2.0
  toast: ^0.3.0
  uuid: ^3.0.6
  flutter_staggered_grid_view: ^0.6.2
  floating_action_bubble: ^1.1.4
  shared_preferences: ^2.0.17
  flutter_share: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
